# Generated by Django 4.1.5 on 2023-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
